### ISSUE TITLE
Ajouter la méthode test_deploy_remote_access conformément à la doc

### ISSUE THREAD

**Issue by tarraschk** [Cyberwatch/cyberwatch_api_powershell#83]
La doc de l'API dit : 
![image](https://user-images.githubusercontent.com/2057917/153258712-2514ae81-08a6-464e-9f1f-51ee7b13dcb7.png)

Or, il apparaît que cette méthode n'existe pas dans le psm1.

Peut-on l'implémenter ?

https://docs.cyberwatch.fr/api/fr/?powershell#verification_du_deploiement_d-une_connexion_sans-agent

**Comment by hezanathos** [comment]
Sujet remis dans le backlog.

**Comment by hezanathos** [comment]
Done
